server:
    port: 12000

management:
  security:
    enabled: false

spring:
  main:
    banner-mode: 'off'
  application:
    name: test

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
# spring.datasource.schema: classpath:/schema.sql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

github:
  api:
    url: 'https://api.github.com'
    access_token: 'ab48081c9aada6b377a83a7caffb3cd82f33c082'

httpConnectionPool:
  timeout: 20000
  maxConnections: 20
  keepAliveTime: 60000