DROP TABLE IF EXISTS `user``;

CREATE TABLE `user`` (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  uuid VARCHAR(250) DEFAULT NULL,
  first_name VARCHAR(250) NOT NULL,
  surname VARCHAR(250) NOT NULL,
  `position` VARCHAR(250) DEFAULT NULL,
  github_url VARCHAR(250) DEFAULT NULL
);